# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quadratic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fquadratic.proto\"/\n\x0c\x43oefficients\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\x12\t\n\x01\x63\x18\x03 \x01(\x02\"4\n\x08Solution\x12\x15\n\rnum_solutions\x18\x01 \x01(\x05\x12\x11\n\tsolutions\x18\x02 \x03(\x02\x32(\n\x03\x61pi\x12!\n\x05solve\x12\r.Coefficients\x1a\t.Solutionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quadratic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COEFFICIENTS._serialized_start=19
  _COEFFICIENTS._serialized_end=66
  _SOLUTION._serialized_start=68
  _SOLUTION._serialized_end=120
  _API._serialized_start=122
  _API._serialized_end=162
# @@protoc_insertion_point(module_scope)
