# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import quadratic_pb2 as quadratic__pb2


class apiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.solve = channel.unary_unary(
                '/api/solve',
                request_serializer=quadratic__pb2.Coefficients.SerializeToString,
                response_deserializer=quadratic__pb2.Solution.FromString,
                )


class apiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def solve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_apiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'solve': grpc.unary_unary_rpc_method_handler(
                    servicer.solve,
                    request_deserializer=quadratic__pb2.Coefficients.FromString,
                    response_serializer=quadratic__pb2.Solution.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class api(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def solve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api/solve',
            quadratic__pb2.Coefficients.SerializeToString,
            quadratic__pb2.Solution.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
